name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use oxr463/setup-leiningen
      uses: oxr463/setup-leiningen@0.0.1
      with:
        exec: |
          lein uberjar && \
          cp "$(find . -name '*.jar')" .   
      
    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest
        clj-kondo: latest
        cljfmt: latest

    - name: Install dependencies
      run: lein deps

    - name: Check format
      run: cljfmt check src 

    - name: Lint
      run: clj-kondo --lint src 
